// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251001185600_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetimeoffset(0)")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset(0)")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ModifiedBy");

                    b.HasKey("Id");

                    b.ToTable("Products", "dbo");
                });

            modelBuilder.Entity("Domain.Product", b =>
                {
                    b.OwnsOne("Domain.ProductRecords.LifeCycleStatus", "LifeCycleStatus", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(64)
                                .IsUnicode(false)
                                .HasColumnType("varchar(64)");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("Domain.ProductRecords.ProductType", "Type", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(64)
                                .IsUnicode(false)
                                .HasColumnType("varchar(64)");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsMany("Domain.VersionProduct", "Versions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("datetimeoffset(0)")
                                .HasColumnName("CreatedAt");

                            b1.Property<string>("CreatedBy")
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("CreatedBy");

                            b1.Property<bool>("IsObsolete")
                                .HasColumnType("bit");

                            b1.Property<DateTimeOffset?>("ModifiedAt")
                                .HasColumnType("datetimeoffset(0)")
                                .HasColumnName("ModifiedAt");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("ModifiedBy");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("ProductId");

                            b1.ToTable("ProductVersions", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.OwnsOne("Domain.ProductSpecification", "Spec", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("VersionId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("Id");

                                    b2.HasIndex("VersionId")
                                        .IsUnique();

                                    b2.ToTable("ProductSpecifications", "dbo");

                                    b2.WithOwner()
                                        .HasForeignKey("VersionId");

                                    b2.OwnsOne("Domain.ProductSpecificationRecords.Amount", "Amount", b3 =>
                                        {
                                            b3.Property<Guid>("ProductSpecificationId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<decimal>("Value")
                                                .HasColumnType("decimal(18,3)");

                                            b3.HasKey("ProductSpecificationId");

                                            b3.ToTable("ProductSpecifications", "dbo");

                                            b3.WithOwner()
                                                .HasForeignKey("ProductSpecificationId");
                                        });

                                    b2.OwnsOne("Domain.ProductSpecificationRecords.Price", "Price", b3 =>
                                        {
                                            b3.Property<Guid>("ProductSpecificationId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<decimal>("Value")
                                                .HasColumnType("decimal(18,2)");

                                            b3.HasKey("ProductSpecificationId");

                                            b3.ToTable("ProductSpecifications", "dbo");

                                            b3.WithOwner()
                                                .HasForeignKey("ProductSpecificationId");
                                        });

                                    b2.OwnsOne("Domain.Taxonomy", "Taxonomy", b3 =>
                                        {
                                            b3.Property<Guid>("ProductSpecificationId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<Guid>("Id")
                                                .HasColumnType("uniqueidentifier");

                                            b3.HasKey("ProductSpecificationId");

                                            b3.ToTable("ProductSpecifications", "dbo");

                                            b3.WithOwner()
                                                .HasForeignKey("ProductSpecificationId");

                                            b3.OwnsOne("Domain.TaxonomyRecords.GenerationRecord", "GenerationRecord", b4 =>
                                                {
                                                    b4.Property<Guid>("TaxonomyProductSpecificationId")
                                                        .HasColumnType("uniqueidentifier");

                                                    b4.Property<string>("Name")
                                                        .IsRequired()
                                                        .HasMaxLength(32)
                                                        .IsUnicode(false)
                                                        .HasColumnType("varchar(32)");

                                                    b4.HasKey("TaxonomyProductSpecificationId");

                                                    b4.ToTable("ProductSpecifications", "dbo");

                                                    b4.WithOwner()
                                                        .HasForeignKey("TaxonomyProductSpecificationId");
                                                });

                                            b3.OwnsOne("Domain.TaxonomyRecords.Kind", "Kind", b4 =>
                                                {
                                                    b4.Property<Guid>("TaxonomyProductSpecificationId")
                                                        .HasColumnType("uniqueidentifier");

                                                    b4.Property<string>("Name")
                                                        .IsRequired()
                                                        .HasMaxLength(32)
                                                        .IsUnicode(false)
                                                        .HasColumnType("varchar(32)");

                                                    b4.HasKey("TaxonomyProductSpecificationId");

                                                    b4.ToTable("ProductSpecifications", "dbo");

                                                    b4.WithOwner()
                                                        .HasForeignKey("TaxonomyProductSpecificationId");
                                                });

                                            b3.OwnsOne("Domain.TaxonomyRecords.ProductCategory", "ProductCategory", b4 =>
                                                {
                                                    b4.Property<Guid>("TaxonomyProductSpecificationId")
                                                        .HasColumnType("uniqueidentifier");

                                                    b4.Property<string>("Name")
                                                        .IsRequired()
                                                        .HasMaxLength(64)
                                                        .IsUnicode(false)
                                                        .HasColumnType("varchar(64)");

                                                    b4.HasKey("TaxonomyProductSpecificationId");

                                                    b4.ToTable("ProductSpecifications", "dbo");

                                                    b4.WithOwner()
                                                        .HasForeignKey("TaxonomyProductSpecificationId");
                                                });

                                            b3.Navigation("GenerationRecord")
                                                .IsRequired();

                                            b3.Navigation("Kind")
                                                .IsRequired();

                                            b3.Navigation("ProductCategory")
                                                .IsRequired();
                                        });

                                    b2.OwnsMany("Domain.Resource", "_resources", b3 =>
                                        {
                                            b3.Property<Guid>("SpecId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<string>("Key")
                                                .HasMaxLength(64)
                                                .IsUnicode(false)
                                                .HasColumnType("varchar(64)");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasMaxLength(2048)
                                                .IsUnicode(true)
                                                .HasColumnType("nvarchar(2048)");

                                            b3.HasKey("SpecId", "Key");

                                            b3.ToTable("ProductSpecificationResources", "dbo");

                                            b3.WithOwner()
                                                .HasForeignKey("SpecId");
                                        });

                                    b2.Navigation("Amount")
                                        .IsRequired();

                                    b2.Navigation("Price")
                                        .IsRequired();

                                    b2.Navigation("Taxonomy")
                                        .IsRequired();

                                    b2.Navigation("_resources");
                                });

                            b1.OwnsOne("Domain.VersionProductRecords.VersionName", "Name", b2 =>
                                {
                                    b2.Property<Guid>("VersionProductId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)");

                                    b2.HasKey("VersionProductId");

                                    b2.ToTable("ProductVersions", "dbo");

                                    b2.WithOwner()
                                        .HasForeignKey("VersionProductId");
                                });

                            b1.OwnsOne("Domain.VersionProductRecords.VersionNumber", "VersionNumber", b2 =>
                                {
                                    b2.Property<Guid>("VersionProductId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Number")
                                        .HasColumnType("int");

                                    b2.HasKey("VersionProductId");

                                    b2.ToTable("ProductVersions", "dbo");

                                    b2.WithOwner()
                                        .HasForeignKey("VersionProductId");
                                });

                            b1.Navigation("Name")
                                .IsRequired();

                            b1.Navigation("Spec")
                                .IsRequired();

                            b1.Navigation("VersionNumber")
                                .IsRequired();
                        });

                    b.Navigation("LifeCycleStatus")
                        .IsRequired();

                    b.Navigation("Type")
                        .IsRequired();

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
